// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Futuristic_Ebike

#include "../ui.h"

void ui_Welcome_screen_init(void)
{
    ui_Welcome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Welcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Welcome, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Welcome, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Welcome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Welcome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BajajLogo = lv_img_create(ui_Welcome);
    lv_img_set_src(ui_BajajLogo, &ui_img_bajaj_png);
    lv_obj_set_width(ui_BajajLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BajajLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BajajLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BajajLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BajajLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
