// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Futuristic_Ebike

#include "../ui.h"


// COMPONENT Label Number4

lv_obj_t * ui_Label_Number4_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Label_Number4;
    cui_Label_Number4 = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Label_Number4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_Number4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_Number4, -8);
    lv_obj_set_y(cui_Label_Number4, lv_pct(74));
    lv_obj_set_align(cui_Label_Number4, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label_Number4, "25#94aeb4 %");
    lv_label_set_recolor(cui_Label_Number4, "true");
    lv_obj_set_style_text_color(cui_Label_Number4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_Number4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_Number4, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL_NUMBER4_NUM);
    children[UI_COMP_LABEL_NUMBER4_LABEL_NUMBER4] = cui_Label_Number4;
    lv_obj_add_event_cb(cui_Label_Number4, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Label_Number4, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Label_Number4_create_hook(cui_Label_Number4);
    return cui_Label_Number4;
}

