// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Futuristic_Ebike

#ifndef _UI_COMP_LABEL_NUMBER4_H
#define _UI_COMP_LABEL_NUMBER4_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label Number4
#define UI_COMP_LABEL_NUMBER4_LABEL_NUMBER4 0
#define _UI_COMP_LABEL_NUMBER4_NUM 1
lv_obj_t * ui_Label_Number4_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
