// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Futuristic_Ebike

#ifndef _FUTURISTIC_EBIKE_UI_H
#define _FUTURISTIC_EBIKE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void Particle1_Animation(lv_obj_t * TargetObject, int delay);
void Particle2_Animation(lv_obj_t * TargetObject, int delay);
void Particle3_Animation(lv_obj_t * TargetObject, int delay);
void Fash_Animation(lv_obj_t * TargetObject, int delay);
void Wave1_Animation(lv_obj_t * TargetObject, int delay);
void Wave2_Animation(lv_obj_t * TargetObject, int delay);
void Off_Animation(lv_obj_t * TargetObject, int delay);
void On_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Welcome
void ui_Welcome_screen_init(void);
extern lv_obj_t * ui_Welcome;
extern lv_obj_t * ui_BajajLogo;
// SCREEN: ui_Driving
void ui_Driving_screen_init(void);
extern lv_obj_t * ui_Driving;
extern lv_obj_t * ui_Speed_Number_2;
extern lv_obj_t * ui_Speed_Number_1;
extern lv_obj_t * ui_Label_Speed;
extern lv_obj_t * ui_Label_kmh1;
extern lv_obj_t * ui_Slider_Speed;
extern lv_obj_t * ui_Group_Speedometer;
extern lv_obj_t * ui_Label_Number1;
extern lv_obj_t * ui_Label_Number2;
extern lv_obj_t * ui_Label_Number3;
extern lv_obj_t * ui_Label_Number4;
extern lv_obj_t * ui_Label_Number5;
extern lv_obj_t * ui_Group_Header;
extern lv_obj_t * ui_Label_Time;
extern lv_obj_t * ui_Labe_AM_PM;
extern lv_obj_t * ui_Label_Temp;
extern lv_obj_t * ui_Label_Celsius;
extern lv_obj_t * ui_ICN_Tmp_Alert;
extern lv_obj_t * ui_ICN_GPS_Alert;
extern lv_obj_t * ui_Group_Footer;
extern lv_obj_t * ui_Button_Group;
extern lv_obj_t * ui_BTN_Driving;
extern lv_obj_t * ui_ICN_Driving;
extern lv_obj_t * ui_BTN_Service;
extern lv_obj_t * ui_ICN_Chck_Ngn;
extern lv_obj_t * ui_BTN_Lock;
extern lv_obj_t * ui_ICN_Lock;
extern lv_obj_t * ui_Group_Driving;
extern lv_obj_t * ui_Group_Content;
extern lv_obj_t * ui_Group_ODO;
extern lv_obj_t * ui_LabeL_ODO;
extern lv_obj_t * ui_Label_ODO_Number;
extern lv_obj_t * ui_Label_ETA_Number;
extern lv_obj_t * ui_Group_Trip;
extern lv_obj_t * ui_Label_Trip;
extern lv_obj_t * ui_Label_Trip_Number;
extern lv_obj_t * ui_Label_km2;
extern lv_obj_t * ui_Group_Max_Speed;
extern lv_obj_t * ui_Label_Max_Speed;
extern lv_obj_t * ui_Label_Max_Speed_Number;
extern lv_obj_t * ui_Label_kmh2;
extern lv_obj_t * ui_Group_AVG_Speed;
extern lv_obj_t * ui_Label_AVG_Speed;
extern lv_obj_t * ui_Label_AVG_Speed_Number;
extern lv_obj_t * ui_Label_kmh3;
extern lv_obj_t * ui_Group_ETA;
void ui_event_BTN_BG4(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG4;
extern lv_obj_t * ui_Label_ETA;
extern lv_obj_t * ui_Label_ETA1;
extern lv_obj_t * ui_Group_Time;
extern lv_obj_t * ui_Label_Time1;
extern lv_obj_t * ui_Label_Arrival_Time_Number1;
extern lv_obj_t * ui_Group_Title;
extern lv_obj_t * ui_Title_BG;
extern lv_obj_t * ui_Label_Driving_Information;
extern lv_obj_t * ui_Group_Service;
extern lv_obj_t * ui_Group_Title1;
extern lv_obj_t * ui_Title_BG1;
extern lv_obj_t * ui_Service;
extern lv_obj_t * ui_Group_Service_Content;
extern lv_obj_t * ui_Group_Service_Alert;
extern lv_obj_t * ui_ICN_Wrench;
extern lv_obj_t * ui_Label_Service_Alert;
extern lv_obj_t * ui_Label_Alert_Service_Number;
extern lv_obj_t * ui_Group_Oil_Alert;
extern lv_obj_t * ui_ICN_Oil;
extern lv_obj_t * ui_Label_Oil_Alert;
extern lv_obj_t * ui_Label_Alert_Oil_Number;
extern lv_obj_t * ui_Group_Oil_Alert1;
extern lv_obj_t * ui_ICN_Oil1;
extern lv_obj_t * ui_Label_Temp_Alert;
extern lv_obj_t * ui_Label_Alert_Temp_Number;
extern lv_obj_t * ui_Group_Notifications;
extern lv_obj_t * ui_Group_Title2;
extern lv_obj_t * ui_Title_BG2;
extern lv_obj_t * ui_Notifications;
extern lv_obj_t * ui_Group_Pin1;
extern lv_obj_t * ui_Button_Pin1;
extern lv_obj_t * ui_Label_1;
extern lv_obj_t * ui_Button_Pin3;
extern lv_obj_t * ui_Label_3;
extern lv_obj_t * ui_Button_Pin9;
extern lv_obj_t * ui_Label_9;
extern lv_obj_t * ui_Button_PinX;
extern lv_obj_t * ui_Image_X;
extern lv_obj_t * ui_Button_PinX1;
extern lv_obj_t * ui_Image_Ok;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bajaj_png);    // assets\bajaj.png
LV_IMG_DECLARE(ui_img_speed_slider_violet_png);    // assets\speed_slider_violet.png
LV_IMG_DECLARE(ui_img_temp_alert_off_png);    // assets\temp_alert_off.png
LV_IMG_DECLARE(ui_img_icon_gps_speed_png);    // assets\icon_gps_speed.png
LV_IMG_DECLARE(ui_img_icon_dashboard_png);    // assets\icon_dashboard.png
LV_IMG_DECLARE(ui_img_checkngin_off_png);    // assets\checkngin_off.png
LV_IMG_DECLARE(ui_img_notification_off_png);    // assets\notification_off.png
LV_IMG_DECLARE(ui_img_menu_on_png);    // assets\menu_on.png
LV_IMG_DECLARE(ui_img_menu_line_png);    // assets\menu_line.png
LV_IMG_DECLARE(ui_img_service_png);    // assets\service.png
LV_IMG_DECLARE(ui_img_oil_alert_off_png);    // assets\oil_alert_off.png
LV_IMG_DECLARE(ui_img_pin_line_png);    // assets\pin_line.png
LV_IMG_DECLARE(ui_img_icn_x_png);    // assets\icn_x.png
LV_IMG_DECLARE(ui_img_icn_ok_png);    // assets\icn_ok.png
LV_IMG_DECLARE(ui_img_particle_1_png);    // assets\particle_1.png
LV_IMG_DECLARE(ui_img_particle_2_png);    // assets\particle_2.png
LV_IMG_DECLARE(ui_img_particle_3_png);    // assets\particle_3.png
LV_IMG_DECLARE(ui_img_water_1_png);    // assets\water_1.png
LV_IMG_DECLARE(ui_img_water_2_png);    // assets\water_2.png

LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Number2);
LV_FONT_DECLARE(ui_font_Small);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
